### ISSUE TITLE
Hello,sir

### ISSUE THREAD

**Issue by FlyDre** [gsarm78/cs230Project#2]
It seems that the output images are not sequential. But I cannot find out why

**Comment by gsarm78** [comment]
Hi. Which images are not sequential? The input image stream should be sequential so the output also is sequential.

**Comment by gsarm78** [comment]
Hi Lyz,

Check the Harvard Dataverse dataset or NEXRAD radars e.g. from here https://radar.weather.gov
BR
National Weather Service Doppler Radar Images<https://radar.weather.gov/>
Latest weather radar images from the National Weather Service
radar.weather.gov

________________________________
